#!/bin/sh
set -e

if [ "$1" = remove ]; then
    if [ -d /run/systemd/system ]; then
        systemctl stop tirage.socket tirage.service || true
    fi
    systemctl --no-reload disable tirage.socket >/dev/null 2>&1 || true
fi
